"""Mathematical and educational analysis engine for verified WinGo draw data."""
import math
from typing import List, Dict, Any

EDUCATIONAL_DISCLAIMER = (
    "EDUCATIONAL STATISTICAL ANALYSIS ONLY: WinGo numbers are generated by independent random trials. "
    "In accordance with probability theory and the Gambler's Fallacy, past occurrences, streaks, and "
    "distribution anomalies do not alter future probabilities or guarantee upcoming outcomes. "
    "This dashboard provides retrospective data analysis and does not offer financial or gambling signals."
)

def classify_color(number: int) -> List[str]:
    """Map number 0-9 to verified colors based on official WinGo rules."""
    if number == 0:
        return ["red", "violet"]
    elif number == 5:
        return ["green", "violet"]
    elif number in (1, 3, 7, 9):
        return ["green"]
    else: # 2, 4, 6, 8
        return ["red"]

def classify_size(number: int) -> str:
    """Classify 0-4 as Small, 5-9 as Big."""
    return "Big" if number >= 5 else "Small"

def compute_signal_for_current_period(current_period: str, records: List[Dict[str, Any]]) -> Dict[str, Any]:
    """Compatibility wrapper around the v1.4 Python signal engine."""
    from .prediction_engine import compute_signal
    return compute_signal(current_period, records)

def compute_window_analysis(records: List[Dict[str, Any]], label: str) -> Dict[str, Any]:
    """Compute verified frequency and distribution metrics for a specified historical window."""
    count = len(records)
    empty_freq = {i: 0 for i in range(10)}
    if count == 0:
        return {
            "periodsAnalyzed": 0,
            "windowLabel": label,
            "bigCount": 0,
            "bigPercentage": 0.0,
            "smallCount": 0,
            "smallPercentage": 0.0,
            "redCount": 0,
            "redPercentage": 0.0,
            "greenCount": 0,
            "greenPercentage": 0.0,
            "numberFrequency": empty_freq,
            "mostFrequent": {"number": 0, "count": 0},
            "leastFrequent": {"number": 0, "count": 0},
            "dataStatus": "DATA UNAVAILABLE",
        }

    big_count = sum(1 for r in records if r.get("size") == "Big")
    small_count = count - big_count
    red_count = sum(1 for r in records if "red" in r.get("colors", []))
    green_count = sum(1 for r in records if "green" in r.get("colors", []))

    freq = {i: 0 for i in range(10)}
    for r in records:
        n = r.get("number", -1)
        if 0 <= n <= 9:
            freq[n] += 1

    most_num = max(freq.items(), key=lambda x: x[1])
    least_num = min(freq.items(), key=lambda x: x[1])

    return {
        "periodsAnalyzed": count,
        "windowLabel": label,
        "bigCount": big_count,
        "bigPercentage": round((big_count / count) * 100.0, 1),
        "smallCount": small_count,
        "smallPercentage": round((small_count / count) * 100.0, 1),
        "redCount": red_count,
        "redPercentage": round((red_count / count) * 100.0, 1),
        "greenCount": green_count,
        "greenPercentage": round((green_count / count) * 100.0, 1),
        "numberFrequency": freq,
        "mostFrequent": {"number": most_num[0], "count": most_num[1]},
        "leastFrequent": {"number": least_num[0], "count": least_num[1]},
        "dataStatus": "VERIFIED",
    }

class AnalysisEngine:
    @staticmethod
    def analyze_history(game_mode: str, records: List[Dict[str, Any]]) -> Dict[str, Any]:
        """Perform comprehensive statistical analysis on historical records."""
        total = len(records)
        if total < 5:
            return {
                "game_mode": game_mode,
                "total_rounds_analyzed": total,
                "analysis_status": "INSUFFICIENT DATA FOR ANALYSIS",
                "sample_window": f"{total} rounds",
                "educational_disclaimer": EDUCATIONAL_DISCLAIMER,
                "number_frequency": {i: 0 for i in range(10)},
                "number_percentages": {i: 0.0 for i in range(10)},
                "size_distribution": {"Big": 0, "Small": 0},
                "size_percentages": {"Big": 0.0, "Small": 0.0},
                "color_distribution": {"green": 0, "red": 0, "violet": 0},
                "color_percentages": {"green": 0.0, "red": 0.0, "violet": 0.0},
                "hot_numbers": [],
                "cold_numbers": [],
                "current_size_streak": {"size": "None", "count": 0},
                "current_color_streak": {"color": "None", "count": 0},
                "streak_records": {"max_big": 0, "max_small": 0, "max_green": 0, "max_red": 0},
                "statistical_entropy": 0.0,
            }

        # 1. Number frequencies 0-9
        freq = {i: 0 for i in range(10)}
        size_counts = {"Big": 0, "Small": 0}
        color_counts = {"green": 0, "red": 0, "violet": 0}

        # For streaks (records are ordered newest to oldest)
        current_size_streak = {"size": None, "count": 0}
        current_color_streak = {"color": None, "count": 0}
        max_big = 0
        max_small = 0
        max_green = 0
        max_red = 0
        
        running_size = None
        running_size_count = 0
        running_color = None
        running_color_count = 0

        # Traverse reverse (oldest to newest) to calculate max streaks
        for i, rec in enumerate(reversed(records)):
            num = int(rec.get("number", 0))
            sz = rec.get("size") or classify_size(num)
            colors = rec.get("colors") or classify_color(num)
            
            # Size streak
            if sz == running_size:
                running_size_count += 1
            else:
                running_size = sz
                running_size_count = 1
                
            if running_size == "Big":
                max_big = max(max_big, running_size_count)
            elif running_size == "Small":
                max_small = max(max_small, running_size_count)

            # Color streak (primary color)
            primary_col = colors[0] if colors else "green"
            if primary_col == running_color:
                running_color_count += 1
            else:
                running_color = primary_col
                running_color_count = 1
                
            if running_color == "green":
                max_green = max(max_green, running_color_count)
            elif running_color == "red":
                max_red = max(max_red, running_color_count)

        # Current streak from latest record
        latest_sz = records[0].get("size") or classify_size(records[0].get("number", 0))
        latest_colors = records[0].get("colors") or classify_color(records[0].get("number", 0))
        latest_col = latest_colors[0] if latest_colors else "green"

        size_streak_count = 0
        for r in records:
            sz = r.get("size") or classify_size(r.get("number", 0))
            if sz == latest_sz:
                size_streak_count += 1
            else:
                break
        current_size_streak = {"size": latest_sz, "count": size_streak_count}

        color_streak_count = 0
        for r in records:
            cols = r.get("colors") or classify_color(r.get("number", 0))
            if cols and latest_col in cols:
                color_streak_count += 1
            else:
                break
        current_color_streak = {"color": latest_col, "count": color_streak_count}

        # Aggregate counts
        for r in records:
            n = int(r.get("number", 0))
            freq[n] = freq.get(n, 0) + 1
            sz = r.get("size") or classify_size(n)
            size_counts[sz] = size_counts.get(sz, 0) + 1
            
            cols = r.get("colors") or classify_color(n)
            for c in cols:
                color_counts[c] = color_counts.get(c, 0) + 1

        # Percentages
        number_pcts = {n: round((cnt / total) * 100.0, 1) for n, cnt in freq.items()}
        size_pcts = {s: round((cnt / total) * 100.0, 1) for s, cnt in size_counts.items()}
        color_pcts = {c: round((cnt / total) * 100.0, 1) for c, cnt in color_counts.items()}

        # Hot & Cold numbers (sorted by frequency)
        sorted_nums = sorted(freq.items(), key=lambda x: x[1], reverse=True)
        hot_nums = [n for n, c in sorted_nums[:3]]
        cold_nums = [n for n, c in sorted_nums[-3:]]

        # Shannon Entropy of 0-9 distribution (max entropy is log2(10) ≈ 3.3219 bits)
        entropy = 0.0
        for cnt in freq.values():
            if cnt > 0:
                p = cnt / total
                entropy -= p * math.log2(p)
        entropy = round(entropy, 3)

        return {
            "game_mode": game_mode,
            "total_rounds_analyzed": total,
            "analysis_status": "ANALYSIS AVAILABLE",
            "sample_window": f"{total} verified rounds",
            "educational_disclaimer": EDUCATIONAL_DISCLAIMER,
            "number_frequency": freq,
            "number_percentages": number_pcts,
            "size_distribution": size_counts,
            "size_percentages": size_pcts,
            "color_distribution": color_counts,
            "color_percentages": color_pcts,
            "hot_numbers": hot_nums,
            "cold_numbers": cold_nums,
            "current_size_streak": current_size_streak,
            "current_color_streak": current_color_streak,
            "streak_records": {
                "max_big": max_big,
                "max_small": max_small,
                "max_green": max_green,
                "max_red": max_red
            },
            "statistical_entropy": entropy,
        }

analysis_engine = AnalysisEngine()
